### ISSUE TITLE
Switch back to Freedesktop Runtime

### ISSUE THREAD

**Issue by RobLoach** [flathub/org.libretro.RetroArch#75]
The KDE Runtime is used because it provides Qt, which is what's used for the WIMP interface. This issue is to allow switching back to the latest Freedesktop Runtime.

## TODO

- [ ] Switch to the latest `freedesktop`
- [ ] Add a Qt5 Flatpak module, or use the [Qt5 Freedesktop Platform](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/issues/356) from TingPing
- [ ] Ensure everything still works

## References
- https://github.com/flathub/org.libretro.RetroArch/pull/74

**Comment by RobLoach** [comment]
https://github.com/flathub/org.libretro.RetroArch/issues/231
